#!/bin/bash -x

orig="root@$ip:$path"
dest="$PWD/backups"

[ -d "$dest" ] || mkdir -p "$dest"

# rsync -vaP    "${orig}" "${dest}/last"
# no usar --inplace
for times in 1 2 3
do
  rsync -a --numeric-ids  "${orig}" "${dest}/last" --exclude_from=nobackup
done

# ssh al server bajar docker compose
# rsync de nuevo
# ssh al server levantar docker compose


d="$(date +%Y-%m-%d-%H-%M-%S)"

mkdir ${dest}/$d
rsync -a ${dest}/last/. ${dest}/$d  --link-dest=${dest}/last

